# # Navigation
# nav:
# - Home:
#   - 'index.md'
#   - 'contributing.md'

# Setup
site_name: FRC Mechanical
repo_name: Docs Source
repo_url: https://github.com/FRCTeam3255/FRC-Mechanical-Guide/tree/main
edit_uri: https://github.com/FRCTeam3255/FRC-Mechanical-Guide/edit/main/docs/
site_author: Tayler Uva

# Theme
theme:
  name: 'readthedocs'
  favicon: assets/favicon.png
  icon:
    logo: assets/favicon.png
use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.tasklist
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      css_class: 'codehilite'
  - toc:
        permalink: "#"

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true

google_analytics:
  - UA-47256977-5
  - auto